---
kind: Service
apiVersion: v1
metadata:
  name: tutum-helloworld-service 
spec:
  selector:
    app: tutum-helloworld
  ports:
    - # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 80
      # Port accessible outside cluster
      nodePort: 30003
  type: LoadBalancer
 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tutum-helloworld-deployment 
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: tutum-helloworld
    spec:
      containers:
        - name: tutum-helloworld-container 
          image: tutum/hello-world
          ports:
            - containerPort: 80